### ISSUE TITLE
Kernelci how to do data interaction with multiple lava master

### ISSUE THREAD

**Issue by hzy729** [kernelci/kernelci-backend#56]
hello，
KernelCI (https://kernelci.org/) operates as a custom frontend across many masters, each of which may have multiple workers.I want to know how to do data interaction with lava？

**Comment by gctucker** [comment]
Each LAVA test job sends its results via an HTTP POST request to the KernelCI backend.  So there needs to be an entry in the backend database with the LAVA lab's details (name...), and an API token which the lab can use to push the data.

This is job for example:
https://lava.collabora.co.uk/scheduler/job/1130260/definition

```
notify:
  criteria:
    status: finished
  callback:
    url: https://api.kernelci.org/callback/lava/boot?lab_name=lab-collabora&status={STATUS}&status_string={STATUS_STRING}
    method: POST
    dataset: all
    token: kernel-ci-callback
    content-type: json
```

The `kernel-ci-callback` string here is used to look up the actual token value from the LAVA authentication table.
